#print ('hello world')
#To access Twitter API
ACCESS_KEY = '1vQF3RQ22pPp3gJjF9Lf6QuE1f'
ACCESS_SECRET_KEY = 'MDAhW0l7ubPig4ytYMW'
CONSUMER_KEY = '6JjHAoRsGDuWSl'
CONSUMER_SECRET_KEY = 'YmOrY44JWSW9ocfRR8'